#! /bin/bash

DATE=$(date +%Y%m%d)

PARENT=/fs2/chet/bash
DIR=$PARENT/bash-$DATE
SRC=/usr/homes/chet/src/bash/src

mkdir $DIR || exit 1

cd $DIR || exit 1

cd $SRC || exit 1

tar cf - . | (cd $DIR ; tar xvpf - )

cd $DIR || exit 1

find . -type f -name '*~' -print | xargs rm -f

find . -type d -name 'savedir' -print | xargs rm -rf

rm parser-built y.tab.c y.tab.h

cd $PARENT || exit 1

tar cvf bash-$DATE.tar bash-$DATE 

gzip -v bash-$DATE.tar
