#! /bin/bash

DATE=$(date +%Y%m%d)

PARENT=/fs2/chet/bash
FROOT=bash-$DATE
DIR=$PARENT/$FROOT
TARF=${FROOT}.tar
SRC=/usr/homes/chet/src/bash/src

fflag= sflag=
while getopts "fs" opt
do
	case $opt in
	f)	fflag=1 ;;
	s)	sflag=1 ;;
	*)	echo "mk-takehome: usage: mk-takehome [-fs]" 2>&1
		exit 2;;
	esac
done

shift $(($OPTIND - 1))

if [ -n "$fflag" ]; then
	rm -rf "$DIR"
fi

mkdir $DIR || exit 1

cd $DIR || exit 1

cd $SRC || exit 1

tar cf - . | (cd $DIR ; tar xvpf - )

cd $DIR || exit 1

find . -type f -name '*~' -print | xargs rm -f

find . -type d -name 'savedir' -print | xargs rm -rf

rm parser-built y.tab.c y.tab.h

rm -f d d? ddd ddd?		# convention for temp diff files

cd $PARENT || exit 1

tar cvf ${TARF} $FROOT

gzip -v ${TARF}

REMHOST=z4

if [ -n "$sflag" ]; then
	scp ${TARF}.gz ${REMHOST}:
fi
