#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# problems with comsub printing and re-parsing with here-documents and compound
# commands in bash-5.2

z=$(
    f1() {
        c <<-!
	!
    }
    f2() {
        :
    }
)

z=$(
    f1() {
        c
    }
    f2() {
        :
    }
)

z=$(
    f1() {
        c <<-!
	!
    }
	:
)

z=$(
    {
        : <<-!
	!
    }
    {
        :
    }
)

z=$(
    for f in 0; do
        : <<-!
	!
    done
    {
        :
    }
)
