#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# printf "%ls" and "%lc" format specifiers for multibyte characters with
# field width and precision in characters instead of bytes
LC_ALL=en_US.UTF-8

V=ಇಳಿಕೆಗಳು
V2=${V:0:2}
V3=${V:0:1}

printf "%ls\n" "$V"
printf "%ls\n" "$V2"
printf "%lc\n" "$V"
printf "%.2ls\n" "$V"

printf "%4.2ls\n" "$V"
printf "%-4.2ls---\n" "$V"

printf "%ls\n" "$V3"
printf "%lc\n" "$V3"

printf "%4.2lc\n" "$V3"
printf "%-4.2lc---\n" "$V3"
