#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# have to run through sed or grep to filter out version information

# let's exercise print-help
help -x

help -- | sed 1d

command help -s help
builtin help -d shift
shift --help
help -s builtin shift

# this hasn't ever been very useful
help -s 'read*'
# but prefix matching is
help -s rea

help :

help -m : | grep -v version

LC_ALL=en_US.UTF-8
help -- | sed 1d

# maybe sometime in the future this will do something
help -- bash
