#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# hash printing, deleting tests
hash -r	# start with empty hash table
hash	# should be error/warning

hash -d notthere
echo $?

hash -p /nosuchdir/nosuchfile cat

hash -t cat
hash -lt cat
hash -l

hash -d cat

hash -d notthere

hash -lt notthere
hash -t notthere

hash -t cat 2>/dev/null
echo $?

# this should fail
hash -p /nosuchdir/nosuchfile cat
cat </dev/null
echo $?
hash -t cat
echo $?

# but with checkhash set, it should not
shopt -s checkhash
cat </dev/null
echo $?
{ hash -t cat | grep cat >/dev/null; } && echo found

hash -r
hash -p / root

hash -r

# assignment to BASH_CMDS[x] should be like hash -p
BASH_CMDS[cat]=/nosuchfile
hash -lt cat
hash -d cat
