umask 022
umask u=r+w
umask -S

umask 022
umask u=r-w
umask -S

umask 022
umask g+u,o+rwx-u
umask -S

umask 022
umask u=r+w,g=wx,o+xr
umask -S

umask 022
umask u+w=r+x
umask -S

umask 022
umask o=u
umask -S

umask 022
umask g=u
umask -S

umask 022
umask u=rwx,u-w
umask -S

umask 022
umask u=xwr
umask -S

umask 022
umask +xwr
umask -S

umask 022
umask a+xwr
umask -S

umask 022
umask +xr
umask -S

umask 022
umask a+xr
umask -S



