#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# more tests for nofork comsub functionality

REPLY=outside

echo ${| REPLY=inside1; }-${| REPLY=inside2; }-$REPLY

echo "BEFORE${| printf -v REPLY '%s\n' AA BB CC; }AFTER"
echo "BEFORE${| printf -v REPLY $'%s\n' AA BB CC; }AFTER"

echo ${ echo unbalanced braces; }}}

echo $(echo combined ${| REPLY=comsubs; })
echo ${ echo $(echo combined ${| REPLY=comsubs; }); }

var=outside
echo ${ var=inside; echo $var; }
echo after: var = $var

( echo ${ echo var=inside; exit 42 ; echo var=inside2; } )
echo after: $? var = $var

( echo ${ echo var=inside; return 42 ; echo var=inside2; } $? )
echo after: $? var = $var
