a()
{
       cat <<-'+' | tr "\t" " " | tr -s " "
               cat - | utkSort
               itkSchemaToColumnType
               atkCacheToColumnType \"$npName\" | atkActiveTableLineSelect
| utkSort
               atkCacheToColumnType \"$npName\" |
atkTransactionTableLineSelect | utkSort
               itkDirToColumnType \"$dirName\" | atkActiveTableLineSelect |
utkSort
               itkDirToColumnType \"$dirName\" | atkActiveTableLineSelect |
utkSort
	+
}

type a

b()
{
	cat /etc/passwd | cat - <<-'+' | tr -s " "
	more
	passwords
	from
	the
	file
	+
}

type b

c()
{
	cat /etc/passwd | tr -s " " | cat - <<-'+' | cat - <<-'foo'
	more
	passwords
	from
	the
	file
	+
last
bunch
of
words
foo
}

type c
