#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
: ${THIS_SH:=$PWD/bash} ${TMPDIR:=/tmp}
POSIX_SH="${THIS_SH} -o posix"

# these are the posix special builtins that take a numeric argument

echo invalid numeric argument
# default mode
for b in exit break continue shift; do
	BUILTIN=$b ${THIS_SH} -c 'set -- a b c; (exit 45); for f in _; do $BUILTIN abcde; done; echo after $BUILTIN: $?' bash
done
${THIS_SH} -c 'func() { return abcde; echo in func: $?; }; func; echo after return: $?' bash

# posix mode
for b in exit break continue shift; do
	BUILTIN=$b ${POSIX_SH} -c 'set -- a b c; (exit 45); for f in _; do $BUILTIN abcde; done; echo after $BUILTIN: $?' bash
done
${POSIX_SH} -c 'func() { return abcde; echo in func: $?; }; func; echo after return: $?' bash

# non-special builtins, no difference
set -o history
HISTFILE=/dev/null
echo a >/dev/null
echo b >/dev/null
echo c >/dev/null
history abcde
echo after history: $?
history 10 42
echo after history: $?
set +o history

# too many arguments

echo too many arguments

TDIR=$TMPDIR/errors-$$
TFILE=errors
mkdir $TDIR || exit 1
cd $TDIR

cat <<\EOF >$TFILE
set -- a b c
(exit 45)
for f in _; do $BUILTIN 42 abcde; done
echo after $BUILTIN: $?
EOF

# default mode
for b in exit return shift break continue; do
	BUILTIN=$b ${THIS_SH} $TFILE	# TFILE for consistent error messages
done
# posix mode
for b in exit return shift break continue; do
	BUILTIN=$b ${POSIX_SH} $TFILE	# TFILE for consistent error messages
done

cd $OLDPWD
rm -rf $TDIR
