: ${TMPDIR:=/var/tmp}
TMPFILE=$TMPDIR/exitcode
trap 'rm -f $TMPFILE' 0

rm -f $TMPFILE
set -e
# we normalize the exit code to accommodate false returning 255 on Solaris
exit_handler() { echo "exit code: $(( $? != 0 ))" ; touch $TMPFILE; }
false() { ! :; }
notfound() { nosuchcommand ; }
syntaxerror() { !:; }

main()
{(
    trap exit_handler 0
    "$@" >> /dev/null 2>&1
)}
main "$@"
echo "after main: should not get here"
