#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# extglob option interaction with other parts of the shell that force
# extended_glob on; only an issue in compatibility mode

shopt -u extglob

BASH_COMPAT=50
shopt extglob

echo $(echo $(echo $(echo $(echo $(echo x) ) ) ) )
shopt extglob

shopt -u extglob

[[ '' = $(shopt extglob >&2) ]]
shopt extglob

shopt -u extglob

[[ foo = $(: $(shopt extglob >&2)) ]]
shopt extglob
