#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# various issues with printing here-documents as part of function bodies

foo()
{
echo begin
if cat << HERE
contents
HERE
then
	echo 1 2
	echo 3 4
fi
}

declare -pf foo

foo()
{
echo begin
while read var << HERE
contents
HERE
do
	echo 1 2
	echo 3 4
done
}

declare -pf foo
unset -f foo
