#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# test various forms of reading here-documents from an alias
shopt -s expand_aliases

# single alias definition contains entire here-document
alias 'heredoc=cat <<EOF
hello
world
EOF'
heredoc

# here-document body continues after alias definition
alias 'headplus=cat <<EOF
hello'
headplus
world
EOF

unalias heredoc headplus

alias head='cat <<END'

head
here-doc line 1
here-doc line 2
END

# here-document delimiter in one alias, body in another
alias head='cat <<\END' body='head
here-document
END'
body

# make sure delimiter is recognized whether the alias ends with a newline or not
shopt -s expand_aliases
alias head='cat <<\END' body='head
here-document
END
'
body

unalias head body
