# issues with local variables and local namerefs post-bash-4.4

f()
{
	local -n ref=var
	local -A ref=([1]=)
#	declare -p ref var
	ref=([2]=)
	declare -p ref var
}

unset ref  var
f

unset ref; var=0
f

unset var
unset -f f

f()
{	
	local -n ref=var
	local -a ref=([1]=)
	ref=([2]=)
	declare -p ref var
}

unset ref var
f

unset ref; var=0
f

unset var
unset -f f

f() { local -n ref=var; local -i ref=([1]=); declare -p ref var; }

unset var
f

var=0
f

unset var
unset -f f

f() { local -n ref=var; local ref=1; declare -p ref var; }

var=0
f

unset var
unset -f f

