#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

printf "%.4s\n" abcde
printf "%.2b\n" abcde

printf "%4d\n" 123
printf "%5i\n" 123
printf "%4o\n" 123
printf "%4x\n" 123
printf "%4X\n" 123
printf "%7b\n" hello
printf "%6s\n" hello
printf "%4u\n" 123
printf "%2c\n" 65

printf "%-4d--\n" 123
printf "%-5i--\n" 123
printf "%-4o--\n" 123
printf "%-4x--\n" 123
printf "%-4X--\n" 123
printf "%-7b--\n" hello
printf "%-6s--\n" hello
printf "%-4u--\n" 123
printf "%-2c--\n" 65
