# test %ls and %lc with multibyte characters

V=ಇಳಿಕೆಗಳು
V2=${V:0:2}
V3=${V:0:1}

printf "%ls\n" "$V" | hexdump -b
printf "%ls\n" "$V2" | hexdump -b
printf "%lc\n" "$V" | hexdump -b
printf "%.2ls\n" "$V" | hexdump -b

printf "%4.2ls\n" "$V" | hexdump -b
printf "%-4.2ls---\n" "$V" | hexdump -b

printf "%ls\n" "$V3" | hexdump -b
printf "%S\n" "$V3" | hexdump -b
printf "%lc\n" "$V3" | hexdump -b
printf "%C\n" "$V3" | hexdump -b

printf "%4.2lc\n" "$V3" | hexdump -b
printf "%-4.2lc---\n" "$V3" | hexdump -b
