#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
LC_ALL=en_US.UTF-8

# this should echo nothing
printf '%ls'
# this should echo a null byte
printf '%lc' | hexdump -b

# this should echo a null byte per posix interp 1647
printf '%lc' '' | hexdump -b

# test %ls and %lc with multibyte characters

V=ಇಳಿಕೆಗಳು
V2=${V:0:2}
V3=${V:0:1}

printf "%ls\n" "$V" | hexdump -b
printf "%ls\n" "$V2" | hexdump -b
printf "%lc\n" "$V" | hexdump -b
printf "%.2ls\n" "$V" | hexdump -b

printf "%4.2ls\n" "$V" | hexdump -b
printf "%-4.2ls---\n" "$V" | hexdump -b

printf "%ls\n" "$V3" | hexdump -b
printf "%S\n" "$V3" | hexdump -b
printf "%lc\n" "$V3" | hexdump -b
printf "%C\n" "$V3" | hexdump -b

printf "%4.2lc\n" "$V3" | hexdump -b
printf "%-4.2lc---\n" "$V3" | hexdump -b

# make sure %ls handles 0 precision the same as %s
printf '[%.0s][%.0ls]\n' X X
