#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
a=4

read -t 2 a < /dev/tty
estat=$?
if [ $estat -gt 128 ]; then
	echo timeout 1: ok
else
	echo $estat
fi

echo $a

sleep 5 | read -t 1 a
estat=$?
if [ $estat -gt 128 ]; then
	echo timeout 2: ok
else
	echo $estat
fi

echo $a

read -t -3 a < /dev/tty
echo $?

echo $a

# the above should all time out
echo abcde | {
	read -t 2 a
	echo $a
}
