#! /bin/sh

PATH=.:$PATH			# just to get the right version of printenv
export PATH
unset ENV

echo Any output from any test indicates an anomaly worth investigating
for x in run-*
do
	case $x in
	$0)	;;
	*.orig|*~) ;;
	*)	echo $x ; sh $x ;;
	esac
done

exit 0
