# testing framework for local variable inheritence

shopt -s localvar_inherit
declare -A var

f() { declare var+=([0]=X); declare -p var; }
f

f() { declare var=([Y]=Y); declare -p var; }; f
f() { declare var+=([Y]=Y); declare -p var; }; f
f() { declare var+=(); declare -p var; }; f
f() { declare var=(); declare -p var; }; f

unset -f f
unset -v var

declare -a var=( [0]=12 )
f() { declare -A var+=([0]=X); declare -p var; }
f

unset -f f
unset a s

a=(X) s=X

f() { local -a a s; declare -p a s; }
f

f() { local a+=(Y) s+=(Y); declare -p a s; }
f

f() { local -a a+=Y s+=Y; declare -p a s; }
f
