#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
swizzle()
{
fd0=0
fd1=1

exec {stdin}<&$fd0
exec {stdout}>&$fd1
}

swizzle
echo $stdin $stdout

read line <&$stdin <<EOF
a
EOF

echo $line
echo $line >&$stdout

type swizzle

exec {stdin}<&-
exec {stdout}>&-

stdin=-1 stdout=-1

declare -n stdin=input
declare -n stdout=output

swizzle
echo ${input} ${output}
echo ${stdin} ${stdout}

exec {stdin}<&-
exec {stdout}>&-

# this should be an error
echo invalid fd >&${output}

exit 0
