#! /bin/sh
#
# mkrbash - make the RBASH file from the `The Restricted Shell' node
#	    of the texinfo manual
#

NODE="The Restricted Shell"
TEXI=bashref.texi
TMPINFO=temp.info
TMPOUT=RBASH.tmp

OUT=${1:-RBASH}

trap 'rm -f $TMPOUT $TMPINFO $OUT; trap '' 0; exit 1' 1 2 3 6 15
trap 'rm -f $TMPOUT $TMPINFO' 0

# create an info file without paragraph indentation
makeinfo --no-split -I../lib/readline/doc --paragraph-indent 0 -o $TMPINFO $TEXI

# write out the text from the `The Restricted Shell' node to $TMPOUT
info --file $TMPINFO --node "$NODE" --subnodes --output $TMPOUT

sed 1,2d < $TMPOUT > $OUT

exit 0
