#! /bin/bash

SRC=/usr/local/src/chet/src/bash/src
REMHOST=jenna
DROPBOX_FOLDER='Dropbox (Personal)'
DROPBOX_HOME=$HOME/$DROPBOX_FOLDER
BOX_FOLDER='Box'
BOX_HOME=$HOME/$BOX_FOLDER
GDRIVE_FOLDER='Google Drive personal'
GDRIVE_HOME=$HOME/$GDRIVE_FOLDER
GFS_FOLDER='Google Drive/My Drive'
GFS_HOME=$HOME/$GFS_FOLDER
ICLOUD_FOLDER='iCloud Drive'
ICLOUD_HOME=$HOME/$ICLOUD_FOLDER

PARENT=/fs2/chet/bash
DATE=$(date +%Y%m%d)
fflag= sflag= dflag= gflag= bflag= Gflag= iflag=

while getopts "bdfgGisp:D:" opt
do
	case $opt in
	b)	bflag=1 ;;
	d)	dflag=1 ;;
	f)	fflag=1 ;;
	g)	gflag=1 ;;
	i)	iflag=1 ;;
	G)	Gflag=1 ;;
	p)	PARENT=$OPTARG
		if [ ! -d "$PARENT" ]; then
			echo "mk-takehome: $PARENT: directory does not exist" 2>&1
			exit 2
		fi ;;
	s)	sflag=1 ;;
	D)	DATE=$OPTARG ;;
	*)	echo "mk-takehome: usage: mk-takehome [-Gdfgs] [-p parent] [-D date] [directory]" 2>&1
		exit 2;;
	esac
done
shift $(($OPTIND - 1))

FROOT=bash-$DATE
DIR=$PARENT/$FROOT

if [ -n "$1" ]; then
	DIR="$1"
	PARENT="${DIR%/*}"
	FROOT="${DIR##*/}"
	if [ -z "$PARENT" ]; then PARENT=. ; fi
	if [ "$PARENT" -ef "$DIR" ]; then PARENT=. ; fi
fi
TARF=${FROOT}.tar

if [ -n "$fflag" ]; then
	rm -rf "$DIR"
fi

trap 'rm -rf "$DIR" ; exit 1' 1 2 3 6 15

mkdir $DIR || exit 1

cd $DIR || exit 1

cd $SRC || exit 1

tar cf - . | (cd $DIR ; tar xvpf - )

cd $DIR || exit 1

find . -type f -name '*~' -print | xargs rm -f

find . -type d -name 'savedir' -print | xargs rm -rf

rm parser-built y.tab.c y.tab.h
# bison -y -d parse.y		# make sure y.tab.h present for dependencies

rm -f d d? ddd ddd?		# convention for temp diff files

cd $PARENT || exit 1

tar cvf ${TARF} $FROOT

gzip -v ${TARF}

if [ -n "$sflag" ]; then
	scp ${TARF}.gz ${REMHOST}:
fi

# box
if [ -n "$bflag" ]; then
	if [ ! -d "$BOX_HOME" ]; then
		HOME=~chet
		BOX_HOME=$HOME/$BOX_FOLDER
	fi
	if [ ! -d "$BOX_HOME" ]; then
		echo "$BOX_HOME: directory not found" >&2
	else
		cp ${TARF}.gz "$BOX_HOME"
	fi
fi

# dropbox
if [ -n "$dflag" ]; then
	if [ ! -d "$DROPBOX_HOME" ]; then
		HOME=~chet
		DROPBOX_HOME=$HOME/$DROPBOX_FOLDER
	fi
	if [ ! -d "$DROPBOX_HOME" ]; then
		echo "$DROPBOX_HOME: directory not found" >&2
	else
		cp ${TARF}.gz "$DROPBOX_HOME"
	fi
fi

# google drive
if [ -n "$gflag" ]; then
	if [ ! -d "$GDRIVE_HOME" ]; then
		HOME=~chet
		GDRIVE_HOME=$HOME/$GDRIVE_FOLDER
	fi
	if [ ! -d "$GDRIVE_HOME" ]; then
		echo "$GDRIVE_HOME: directory not found" >&2
	else
		cp ${TARF}.gz "$GDRIVE_HOME"
	fi
fi

# google drive file stream
if [ -n "$Gflag" ]; then
	if [ ! -d "$GFS_HOME" ]; then
		HOME=~chet
		GFS_HOME=$HOME/$GFS_FOLDER
	fi
	if [ ! -d "$GFS_HOME" ]; then
		echo "$GFS_HOME: directory not found" >&2
	else
		cp ${TARF}.gz "$GFS_HOME"
	fi
fi

# google drive file stream
if [ -n "$Gflag" ]; then
	if [ ! -d "$GFS_HOME" ]; then
		HOME=~chet
		GFS_HOME=$HOME/$GFS_FOLDER
	fi
	if [ ! -d "$GFS_HOME" ]; then
		echo "$GFS_HOME: directory not found" >&2
	else
		cp ${TARF}.gz "$GFS_HOME"
	fi
fi

# iCloud
if [ -n "$iflag" ]; then
	if [ ! -d "$ICLOUD_HOME" ]; then
		HOME=~chet
		ICLOUD_HOME=$HOME/$ICLOUD_FOLDER
	fi
	if [ ! -d "$ICLOUD_HOME" ]; then
		echo "$ICLOUD_HOME: directory not found" >&2
	else
		cp ${TARF}.gz "$ICLOUD_HOME"
	fi
fi
