.\" This is a hack to force bash builtins into the whatis database
.\" and to get the list of builtins to come up with the man command.
.TH BASH_BUILTINS 1 "1993 September 16" GNU
.SH NAME
bash, :, ., alias, bg, bind, break, builtin, bye, case, cd, command,
continue, declare, dirs, echo, enable, eval, exec, exit, export, fc,
fg, for, getopts, hash, help, history, if, jobs, kill, let, local,
logout, popd, pushd, pwd, read, readonly, return, set, shift, source,
suspend, test, times, trap, type, typeset, ulimit, umask, unalias,
unset, until, wait, while \- bash built-in commands, see \fBbash\fR(1)
.SH BASH BUILTIN COMMANDS
.nr zZ 1
.so bash.1
.SH SEE ALSO
bash(1), sh(1)
